config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'pages#index'

get "/service", to: "services#index"
get "/apple", to: "apples#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
def index
end
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/apples/index.html.erb
<div class="boss"> 

    <div class="tile is-ancestor">
        <div class="tile is-parent is-4 avatar">
            <div class="tile is-child center">
                <img id="fy" src="https://i.imgur.com/jU7TQB3.jpg" alt="">

                <p>  
                    <h1 class="title">Ryan</h1>
                    <h6 class="intro">

                    I have a passion for language learning and I decided to use my free time to learn japanese in 2018.
                    I participated  in my first time Japanese language ability test after about one and half year since I'd started this challenge.
                    Luckily everything turned out good.
                    I had my Japanese N1 certification in the first try.
                    After that I started to work as a Japanese translator in a Taiwan TV station.
                    I provide instant translations from Japanese to chinese for TV news or special programs.
                    </h6>
                    <div class="section icon">
                        <%= link_to "https://line.me/ti/p/I7Jjglzj2d" do %>
                        <i class="fab fa-line line"></i>
                        <% end %>
                        <%= link_to "mailto:geographicpenguin@gmail.com" do %>
                        <i class="fas fa-envelope email"></i>
                        <% end %>
                    </div>

                </p>
            </div>
        </div>

        <div class="tile is-vertical  is-parent is-8 detail">
                <div class="tile is-child">  
                        <h1 class="title center has-text-primary">Skill</h1>
                        
                        <div class="has-text-primary is-size-4">Foreign language:</div> 
                        <table class="table is-fullwidth tableone">
                          <thead>
                            <tr>
                              <th>language</th>
                              <th>level</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>Chinese</td>
                            <td>native speaker </td>
                          </tr>
                          <tr>
                            <td>Japanese</td>
                            <td>N1 certification</td>
                          </tr>
                          <tr>
                          <td>English</td>
                          <td>Toeic 810</td>
                        </tr>
                        </table>
                </div>
                
                <div class="tile is-child"> 

                        <div class="has-text-primary is-size-4">Computer skill:
                        </div>
                        <table class="table is-fullwidth tabletwo">
                          <thead>
                            <tr>
                              <th>frontend</th>
                              <th>tool</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>html</td>
                            <td>[VSC]</td>
                          </tr>
                          <tr>
                            <td>css</td>
                            <td>[bulma][scss]</td>
                          </tr>
                          <tr>
                            <td>js</td>
                            <td>[jQuery]</td>
                          </tr>
                          <thead>
                            <tr>
                              <th>backend</th>
                              <th>tool</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>ruby on rails</td>
                            <td>[WSL2]</td>
                          </tr>
                          <tr>
                            <td>git</td>
                            <td>[gitHub]</td>
                          </tr>

                        </table>




 
                </div>
            </div>
        </div>


        <hr>

        <div class="columns is-vcentered">
          <div class="column is-5 ">
            <figure class="image is-16by9">
              <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0kXekbcQgcw" frameborder="0" allowfullscreen></iframe>
            </figure>
          </div>
          <div class="column king">
            <h1 class="title center real has-text-primary">
            Translation experience</h1>
            <h1 class="is-size-5 has-text-left" class="example">
                <strong> Ms. Chen </strong> is a famous Taiwan announcer.
                She hosts a TV program named <strong> one type of styles </strong>.
                Ms. Chen and her team visited Japan crossing from Honshu into Shikoku in 2019.
                They interviewed native residents leaving in small towns of Japan.
                I had the honor to take on the role of subtitle translator for the special program.
                I translated colloquial Japanese to Chinese sentences which were more easy to read by audiences.
            </h1>
          </div>
        </div>
    <hr>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/VgaSJUMU1Xg" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">Coronavirus outbroke in Japan</p>
        <p>2020 Tokyo Olympic counter challenges</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/iyHxQ4Uc5co" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">History reason for Japan's love for Olympic </p>
        <p>2020 Tokyo Olympic postponed or cancelled could cause tremendous impact on Japan Economy</p>
      </div>
    </div>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0XPut5iFzqQ" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">The final decision</p>
        <p>overwhelmed by global epidemic</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/HewUKh4Yw4g" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">Virus changed people's lives</p>
        <p>COVID-19 damaged Economy of Japan</p>
      </div>
    </div>

    <hr>


    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewWeb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/671be2009c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= render 'shared/frontend/bigpicture' %>


    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="boss"> 

    <div class="tile is-ancestor">
        <div class="tile is-parent is-4 avatar">
            <div class="tile is-child center">
                <img id="fy" src="https://i.imgur.com/jU7TQB3.jpg" alt="">

                <p>  
                    <h1 class="title">王建崙 Ryan</h1>
                    <h6 class="intro">對語言抱有熱誠，利用閒餘時間自修日文，一年半後首度挑戰日語能力試驗，順利獲得日語能力檢定N1證書，擁有一年的日文編譯實務經驗，提供電視新聞以及節目的日中翻譯，長期追蹤日本新聞快訊。
                    </h6>
                    <div class="section icon">
                        <%= link_to "https://line.me/ti/p/I7Jjglzj2d" do %>
                        <i class="fab fa-line line"></i>
                        <% end %>
                        <%= link_to "mailto:geographicpenguin@gmail.com" do %>
                        <i class="fas fa-envelope email"></i>
                        <% end %>
                    </div>

                </p>
            </div>
        </div>

        <div class="tile is-vertical  is-parent is-8 detail">
                <div class="tile is-child">  
                        <h1 class="title center has-text-primary">工作技能</h1>
                        
                        <div class="has-text-primary is-size-4">語言能力:</div> 
                        <table class="table is-fullwidth tableone">
                          <thead>
                            <tr>
                              <th>語言</th>
                              <th>程度</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>日語</td>
                            <td>N1</td>
                          </tr>
                          <tr>
                            <td>英語</td>
                            <td>多益810分</td>
                          </tr>
                        </table>
                </div>
                
                <div class="tile is-child"> 

                        <div class="has-text-primary is-size-4">資訊能力:
                        </div>
                        <table class="table is-fullwidth tabletwo">
                          <thead>
                            <tr>
                              <th>前端技術</th>
                              <th>工具</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>html</td>
                            <td>[VSC]</td>
                          </tr>
                          <tr>
                            <td>css</td>
                            <td>[bulma][scss]</td>
                          </tr>
                          <tr>
                            <td>js</td>
                            <td>[jQuery]</td>
                          </tr>
                          <thead>
                            <tr>
                              <th>後端技術</th>
                              <th>工具</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>ruby on rails</td>
                            <td>[WSL2]</td>
                          </tr>
                          <tr>
                            <td>git</td>
                            <td>[gitHub]</td>
                          </tr>

                        </table>




 
                </div>
            </div>
        </div>


        <hr>

        <div class="columns is-vcentered">
          <div class="column is-5 ">
            <figure class="image is-16by9">
              <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0kXekbcQgcw" frameborder="0" allowfullscreen></iframe>
            </figure>
          </div>
          <div class="column king">
            <h1 class="title center real has-text-primary">翻譯經驗</h1>
            <h1 class="is-size-5 has-text-left" class="example">
            台灣新聞主播<strong>陳雅琳</strong>老師，所主持的專題節目<strong>有一種Style</strong>，在2019年時造訪日本，實地訪問日本小鎮居民，進行拍攝報導，足跡從日本本州橫跨到四國，我有榮幸為陳雅琳老師的節目承接文字翻譯工作，為接受訪談的日本居民，將口語化的日文翻譯成中文母語者習慣的語句，進行流暢的日中翻譯。
            </h1>
          </div>
        </div>
    <hr>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/VgaSJUMU1Xg" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">疫情重創日本</p>
        <p>2020東京奧運恐生變</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/iyHxQ4Uc5co" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">日本奧運歷史情懷</p>
        <p>2020東京奧運取消或延期都將衝擊經濟</p>
      </div>
    </div>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0XPut5iFzqQ" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">最艱難的決定</p>
        <p>東京奧運難敵全球疫情</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/HewUKh4Yw4g" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">疫情影響生活</p>
        <p>新型冠狀病毒疫情衝擊日本經濟</p>
      </div>
    </div>

    <hr>


    </div>

app/views/services/index.html.erb
<div class="boss"> 

    <div class="tile is-ancestor">
        <div class="tile is-parent is-4 avatar">
            <div class="tile is-child center">
                <img id="fy" src="https://i.imgur.com/jU7TQB3.jpg" alt="">

                <p>  
                    <h1 class="title">けんりん Ryan</h1>
                    <h6 class="intro"> 
                    外語を学ぶことに情熱を持っています。２０１８年から私が空いた時間を利用して、日本語を自学自習しました。２０１９年、日本語の勉強を始めるから一年半後。私が日本語能力試験を参加し、合格しました。N1レベルの認定書を頂きました、その後テレビで通訳を務めました。私が日本語を中国語にやくしまして、報道番組に提供しました。日本のニュースをフォローアップして来ました。
                    　
                    </h6>
                    <div class="section icon">
                        <%= link_to "https://line.me/ti/p/I7Jjglzj2d" do %>
                        <i class="fab fa-line line"></i>
                        <% end %>
                        <%= link_to "mailto:geographicpenguin@gmail.com" do %>
                        <i class="fas fa-envelope email"></i>
                        <% end %>
                    </div>

                </p>
            </div>
        </div>

        <div class="tile is-vertical  is-parent is-8 detail">
                <div class="tile is-child">  
                        <h1 class="title center has-text-primary">スキル</h1>
                        
                        <div class="has-text-primary is-size-4">語学力:</div> 
                        <table class="table is-fullwidth tableone">
                          <thead>
                            <tr>
                              <th>外語</th>
                              <th>レベル</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>中国語</td>
                            <td>母語</td>
                          </tr>
                          <tr>
                            <td>日本語</td>
                            <td>N1認定書</td>
                          </tr>
                          <tr>
                          <td>英語</td>
                          <td>トーイック８１０点</td>
                        </tr>
                        </table>
                </div>
                
                <div class="tile is-child"> 

                        <div class="has-text-primary is-size-4">ITスキル:
                        </div>
                        <table class="table is-fullwidth tabletwo">
                          <thead>
                            <tr>
                              <th>フロントエンド</th>
                              <th>ツール</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>html</td>
                            <td>[VSC]</td>
                          </tr>
                          <tr>
                            <td>css</td>
                            <td>[bulma][scss]</td>
                          </tr>
                          <tr>
                            <td>js</td>
                            <td>[jQuery]</td>
                          </tr>
                          <thead>
                            <tr>
                              <th>バックエンド</th>
                              <th>ツール</th>
                            </tr>
                          </thead>
                          <tr>
                            <td>ruby on rails</td>
                            <td>[WSL2]</td>
                          </tr>
                          <tr>
                            <td>git</td>
                            <td>[gitHub]</td>
                          </tr>

                        </table>




 
                </div>
            </div>
        </div>


        <hr>

        <div class="columns is-vcentered">
          <div class="column is-5 ">
            <figure class="image is-16by9">
              <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0kXekbcQgcw" frameborder="0" allowfullscreen></iframe>
            </figure>
          </div>
          <div class="column king">
            <h1 class="title center real has-text-primary">翻訳経験</h1>
            <h1 class="is-size-5 has-text-left" class="example">
                台湾有名な女子アナウンサー<strong>陳雅琳</strong>さん
                担当している番組<strong>ひとつのスタイル</strong>が２０１９年の時に日本に行きました。
                番組が本州と四国で撮影したり町の住民たちへの訪問をしました。
                私がこの番組字幕の日中翻訳を委託されました。
                訪問をうけた日本の方の話を中国母語話者も受け入れる言葉に訳して、
                スムーズに日中翻訳をしました。
            </h1>
          </div>
        </div>
    <hr>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/VgaSJUMU1Xg" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">新型コロナの感染が日本で拡大する</p>
        <p>キャンセルとか延期とか　２０２０五輪見えない未来</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/iyHxQ4Uc5co" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">日本がオリンピックへの歴史思い</p>
        <p>２０２０五輪日程調整による日本経済への影響</p>
      </div>
    </div>

    <div class="columns">
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/0XPut5iFzqQ" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">もっとも厳しい決断</p>
        <p>感染症が世界中で拡散しており　東京五輪延期決めた</p>
      </div>
      <div class="column is-3">
        <figure class="image is-16by9">
          <iframe class="has-ratio" width="640" height="360" src="https://www.youtube.com/embed/HewUKh4Yw4g" frameborder="0" allowfullscreen></iframe>
        </figure>
      </div>
      <div class="column">
        <p class="has-text-primary">新型コロナ日常生活への影響</p>
        <p>日本経済への悪い影響</p>
      </div>
    </div>

    <hr>


    </div>

app/views/shared/frontend/_bigpicture.html.erb
<figure class="image">
  <img src="https://i.imgur.com/vDTdXI9.jpg">
</figure>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
  <%= link_to root_path ,class:"navbar-item" do %>
    <h1 class="title">Home</h1>
  <% end %>


</div>

<div class="navbar-menu is-active" id="navMenu">
  <div class="navbar-end servicedown">
      <%= link_to service_path ,class:"navbar-item" do %>
        <h1>日本語</h1>
      <% end %>
      <%= link_to apple_path ,class:"navbar-item" do %>
        <h1>English</h1>
      <% end %>
  </div>
</div>
</nav>